image:
  file: .gitpod.Dockerfile
ports:
  - port: 3000
    onOpen: open-preview
  - port: 6080
    onOpen: ignore
tasks:
  - init: pip3 install -r requirements.txt
    command: |
      cd src/
      python3 main.py 
vscode:
  extensions:
    - ms-python.python